### ISSUE TITLE
Fog of war walls are displayed as fog

### ISSUE THREAD

**Issue by oconn** [willowtreeapps/battlebots#52]
This bug occurs when a bot is placed next to a wall at a 45° angle. The wall at 45° is returned as fog.

```
? ? ? ? ? _ + _ _ _
? ? ? @ @ _ _ _ _ ?
_ ? ? ? _ _ _ + ? ?
+ _ ? ? _ _ ? ? ? ?
_ _ _ _ B @ ? ? ? ?
_ _ + _ _ _ ? ? ? ?
_ _ _ _ _ _ @ ? ? ?
_ + _ _ - _ ? ? ? ?
_ _ _ _ + _ _ ? ? ?
_ _ + _ _ _ _ _ ? ?
_ _ _ _ + _ _ _ ? ?
```

cell (3, 3) in this arena is a block.

**Comment by oconn** [comment]
When applying the occlusion logic to the user partial I was able to gain a little more context around this bug. 

![image](https://cloud.githubusercontent.com/assets/4649439/16458411/f4dac13e-3dec-11e6-80df-88af28c4bc44.png)

while the bot is not depicted in this image, it is located at position (10,10). (note row ten is printed a half step to the left)

It appears that (10,9) is casting fog on all the walls running from (0,9) to (9,9), or is interpreting them as walls an is converting them to fog. Same applies to the wall running from (11,10) to (11,20)

**Comment by thoughtmanifest** [comment]
And what does the non-occluded arena look like?

**Comment by oconn** [comment]
This is not the exact arena, however same concept

![image](https://cloud.githubusercontent.com/assets/4649439/16460194/448ba412-3df4-11e6-87b7-cc70faf9b45b.png)

**Comment by thoughtmanifest** [comment]
I should have been more specific, I was looking for the non-occluded version of the player arena in order to see what were actually walls and what weren't.

Also, could this have been affected by the use of differing interpretation of the x and y axes?

**Comment by oconn** [comment]
So I fixed all the x y interpretations in the PR that I have up now. Each row represents a `y` axes.

![image](https://cloud.githubusercontent.com/assets/4649439/16461010/63b6f9dc-3df8-11e6-9855-edb06b1e6967.png)

![image](https://cloud.githubusercontent.com/assets/4649439/16461016/6ba9c78c-3df8-11e6-9a87-1f14754053b4.png)

**Comment by thoughtmanifest** [comment]
I'm glad to see those were actually walls, I was worried the 9 and 11 axes weren't walls.  I'll see what I can do about that this evening unless @dehli has some thoughts.

re: Arena axes, so you're able to use (get-in arena [x y]) to return the x,y coordinate? or is it (get-in arena [y x])?

**Comment by oconn** [comment]
```clj
(defn get-item
  "gets an item based off of given coords"
  [[x y] arena]
  (get-in arena [y x]))
```

I'd use this method under `battlebots.arena.utils`. We are now testing all of those funcitons
